import { Link } from "react-router-dom";

export default function Ministory1EpisodeIV() {
  return (
    <div className="max-w-[720px] mx-auto px-6 py-20">
      <div className="gold-rule mb-6" aria-hidden="true" />
      <Link
        to="/bookshelf/ministories/damsellete-of-the-wind"
        className="font-body text-[10px] tracking-widest uppercase text-[#4a4844] hover:text-[#c9a84c] transition-colors duration-200 inline-block mb-6"
      >
        ← Back to Damsellete of The Wind (Raeya&#39;s Ministory)
      </Link>
      <p className="font-body text-xs tracking-[0.25em] text-[#c9a84c] uppercase mb-2">Hibryds · Damsellete of The Wind</p>
      <h1 className="font-display text-[clamp(1.3rem,1rem+1.25vw,2rem)] text-[#f2ebeb] mb-3 leading-tight">Episode IV — Timed Revival</h1>
      <p className="font-body text-xs text-[#7a7670] italic mb-12">The Divine Realm</p>

      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `The portal I went through shut behind me, and I was brought into a vast, golden realm. It had faint-yellow skies, white clouds, and the ground, white and golden. There was a long, infinite golden bridge that panned to the far reaches of the realm. I looked around and it was a scene of divinity. My sense of pain and sadness disappeared, and peace was brought to me. Even though I wasn’t in my physical form, I felt at peace, in a haven like this.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Welcome to the Divine Realm,” Zohl welcomed me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I didn’t know what to say. I was speechless. Everything about this realm felt good. It was good. It is good. It was like a state of what was, what is, and what will be.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Speechless?” He laughed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I….,” I uttered, a little shy a first.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Uhm…,”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Although my sense of other emotions like disturbed and annoyance were faint, I had questions. I was curious.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What…am..I..?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I looked down at my hands, arms, and body. It was like I could see through myself.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What are you?” Zohl rephrased.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You’re now a <em>Soul</em>.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Wait, I thought Souls and Spirits were the same thing!” I was surprised. He gestured to me for a moment. With his mind, he used his powers to lift some beds of cloud up into the air. As they did, Zohl placed my physical body on them. He gently laid it down with ease, being careful. It looked like my body was positioned in a way like how coffins work.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Now, where was I?” He sarcastically said.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Normally, this information is disclosed, but for you, I will make an exception!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Spirits and Souls may be the same to your earthly knowledge, but they are entirely unique entities,” he explained,`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Outsiders, much like humans and creatures alike, run on Souls. Souls are a manifestation of life, given by an ancient spirit, Aurora Rimaea (known as the Spirit of Life). Us Spirits differ from souls since we are manifested from this place, by our creator, King Nhavah.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You probably know, but on Hetra, partners in marriage can reproduce. This is because of how Souls operate- they reproduce, learn, and survive. We Spirits can’t. We cannot procreate, but we can learn; survive, create, clone, empower, and modify. We don't have full control over souls since they are living beings. Our code is to create, not destroy.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“However, we are not immortal. Our powers give us life. Without these, we will die.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I had never known this before. Out of my years on Hetra, I’ve never stumbled or studied about this type of topic. But I was pleased that I could know this.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“So that means since I’m in my soul appearance, only you Spirits can see us and interact with us, right?” I clarified.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You are correct!” Zohl gave me a high-five.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Part of this wasn’t in my plans. Untimed and unplanned. If I had reacted before you sacrificed yourself, Kydel wouldn’t be in this state,” he confessed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Wait…,” I realized something, wanting to take back that high-five. Something doesn’t add up correctly…`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Does that mean, that you, a <em>Spirit of Creation</em>, created the planet that I live on?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He laughed like I called him out. He somehow felt relieved.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Yes. Planet Hetra is my creation,” he confirmed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You were the one to give Kydel his powers...” I continued, catching on. He had a nervous reaction to my deduction. It looked like he was scared about what was to come.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“And thus, when Planet Hetra was still in its prime, perhaps one of you went on a rampage. This resulted with Rachnaea and her absurd powers. You did say that you can clone yourself, right? So I would assume that one of your clones went rogue…”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Then later down the road, you had no choice but to act accordingly to your, ‘plan,’ which resulted in today’s events!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Hold on a damn minute!! DID you really take advantage of Kydel along with his powers, just to kill the damn witch?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He said nothing, which I took that as a yes.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Kydel TRUSTED you! He thought you were his <em>friend</em>! Not only that, but a guide! A teacher! Now think about what you did!!” I yelled at him, disappointed. I grabbed him by his shoulder and leaned him into my level, not just my eyes, but that of a human.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You betrayed his trust! Even at the last minute, you asked him if he can trust you! What kind of spirit complexity do you have?! Is your head too high in the clouds?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I – hey!! Don’t say tha-“ Zohl tried to reason with me but I had to put him in his place. I shoved him down onto the floor just as he tried to reach for me. I was angry, no–mad, that his huge egotistical complexity is what led him to this horrible outcome!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Now that begs the question! How can I <em>expect </em>you to return the <em>favor</em> for me since he begged <em>mercilessly </em>at his feet?!” I yelled at him, where my voice could reach every vast corner of the realm. Not only I caught up with Zohl’s antics, I could see why Kydel was angry at him. I don’t even know if I could trust him right now, since he himself was deluded with his own actions.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Please, Raeya, everything I say is true!” he defended himself.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I..had no choice but to use him!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“For my own…..selfish….”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“….actions..”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I let out an audible gasp. My heart dropped after I heard those words come out of his mouth. Hearing him painfully admit that made me furious.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Hypocrite…!” I uttered under my breath. He heard that, and his voice hesitated before a word came from his mouth, “…..ouch…”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I wanted a full story about what had happened before Kydel got his powers, his abilities, and his new awakening.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Tell me everything!” I demanded with a crossed and stern look. I had called him out on his actions since I saw through it. Zohl’s secrets were his plans, his truth. I wanted to hear it from him straight until he apologized to Kydel. So, he told me everything, excluding his role as a Spirit.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“But I—” I cut him off, and with my chest, I demanded again by saying: “<strong><em>NOW</em></strong>!!!”`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Moments later, he finished. Now I understood why he did what he had to do. Rachnaea used one of his clones to gain advantage of their powers. She lived as long as she could until Kydel defeated her, well, killed. Even though his past actions were slightly planned, he didn’t see that much further into it. But when the time came, he had a plan to turn Kydel into a hibryd. And in time, it pushed him to the extent to make things right with his past actions.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `A simple direwolf itself has immense strength and power, which is common knowledge on Hetra. And when Kydel came along, Zohl had given him more dangerous ones! What the hell was he thinking?!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You owe him an apology!” I was disappointed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Do I really have to…?” he was hesitant.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What if he’s mad..? Upset?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Spirits aren’t supposed to be that forgivi-”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Hearing him say that, I slapped him in his face. He defaulted back into his ways of thinking and I wasn’t having it. Complexity? No, that is a complete lie! He’s way too high up in the clouds!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Skærøl Ghrünpæarou!!” I cursed at him, “is your head a screw loose?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You’re a Spirit! A Spirit!!! A Divine SPIRIT of CREATION!!! What makes you think you can’t say sorry to him?!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I—” I cut him off, “DID I STUTTER?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Didn’t you say The King manifested spirits alike like you?! What about all the traits you have?!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I wasn’t done with him yet. He wanted his plan to be perfect, but it only unfolded with chaos. That is something I can’t have in my relationship with him. Not as a partner, but as someone who I genuinely look up to.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He has to change for the better because all he has been doing is having his spirit complexity torture him! Not only it will ruin his relationship with Kydel, it would break my viewpoint of him as a brother! Well, a spiritual brother, not related in any ways (lol).`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Zohl, I know you’re a Divine Spirit! A Spirit of Creation! And also an observer, right? You like to watch how humanity develops, right?” I asked him as I questioned. He nodded in response, unable to think of anything else.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“But all of us humans…? We’re not near damn perfect like you!! This plan you call “<em>perfect?</em>” It's not meant to be perfect!” I scolded him. He backed down more and he lowered his head towards me, which was what I wanted to see. I could have the right to be angry at him for how he treated Kydel like a one way street. But I don’t want to be angry.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What makes you think that every outline or goal has to be that satisfying? So that you can go back and not learn from it? Perfection is flawless! Without holes!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“A plan or goal that has holes or flaws, it’s not meant to be perfect! And your way of doing things up until now…it’s all unethical! If you can’t get your head out of that mindset, my friendship with you would be gone this instant, and I don’t want that to happen!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Zohl. Please. I care about you as a friend. You’re unique in your own ways. But that? It’s not right. Now, I don’t want to keep lecturing you forever, or whatever punishment will be casted upon you. I just want you to know what you did isn’t right!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Giving him a piece of my mind, he couldn’t respond at all. His heart was full of shame and guilt because I could hear it beat red and slowly due to my Sylph powers.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `But since he couldn’t utter a single response, I wanted to reassure him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Zohl, look at me,” I ordered him. He held his head up.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I value morals and friendship. Trust me! I have my hardships and so do others! Learning from mistakes is what makes you human! Please, be humble to yourself and learn from your mistakes!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What I’m telling you is to have a sense of humanity! See each other for who they are! Not from their surface, but from their heart!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I saw him sink to his knees, his head slightly lower to me. He wanted to respond, but didn’t know how. He shouldn't even be bowing to me. I’m just a measly nhuemyn (pffft~)!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Oh dear my me. Zohl, please listen to her,” a voice appeared from behind. It had startled me because the voice had such an elegant and soft tone to it. Who was that?`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“My King…!” Zohl bowed before him. Wait, the King? As in King Nhavah?! I turned around and wanted to bow, but he gestured me not to. It looked like he had heard <em>everything</em>. Also, he's big. Like lion turtle big.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I have heard everything from afar and I have to agree with her,” The King approached us.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Had I wished to judge you based on your actions up until now, you would be casted out of this realm immediately. But since Raeya was here, she was quick to call you out.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `<em>“Thank you~</em>”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Hearing him thank me made me realize that I was right. I only did this out of concern, not pity. And with The King being a grand being, I can’t begin to imagine what would happen to Zohl, who is still my friend nonetheless.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Please, think about this,” I said, holding my hand out to him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He took my hand and got up, his voice stuttered, not knowing how to convey his feelings.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’m sorry….Raeya,” He apologized to me, but I shook my head saying that it’s fine.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I realize that you’re right. If I had kept doing what I was doing, I would be a completely different person, and you wouldn’t want that, along with Kydel.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I really treasure you two, because you guys are my friends. Genuine friends I’ve made as a person of being. And even when I was observing the two of you, I had this urge not to intervene, but I couldn’t. In the end, I was made a fool.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I want this new chance to change, and I’m willing to do anything, even if it means risking my role as a Spirit. Thanks Raeya. I can’t do this without you.”`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I smiled knowing that Zohl fully acknowledged that mistakes were made, and that he could use that experience to learn from. Today marks the start for him. I looked around the realm because this place was still new to me. I kind of want a tour!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Shuffling around, I wanted to go back to the real world. I don’t want to stay here for too long. There was this weird tender awkwardness of silence between me and him, and I didn’t know what else to bring up. But looking around the place, it felt like there were so many different divine beings here. Not just King Nhavah. I could hear chatter from miles away due to my enhanced ears.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I could hear heartbeats.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I could hear the skies singing with praise.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Zohl guided me along down for a tour at first. There were lots of different celestial buildings. There was a huge castle of gold and bronze. The clouds looked like cotton candy. Paved roads.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Would this…be considered the afterlife…?” I asked him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Hmmm….not really,” he responded with clarity.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“This place is more for us beings to live in! The afterlife you call is actually a realm within this realm that is the home of Aurora Rimaea, The Life Spirit of Life, and Morhv, The Spirit of Death. That’s their domain and also what you call ‘The Afterlife.’”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Though of course, there aren’t any gates between this place and The Afterlife. After all, souls like you can come into this place freely to chat with others!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“No exclusivity. Everything here will be open as possible!”`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `When we walked and toured around more, I spotted a cute little place that the realm had. It was flowery. Soft like cotton and had a very familiar structure similar to where I lived. I skittishly went towards it, all curious and whatnot. It smelled familiar. Looked familiar. Like a sense of home. My main body was still on the cloud he tethered with us, but he hid it with invisiblity so that I wouldn’t get distracted. Hah. Rude much? But I get it. He needs to preserve it for the time being.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What’s this….?” I asked him with a hesitant voice.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Oh…um…that’s….how do I say this—” I heard his voice get cut off and a voice from behind scared us, and I jumped right behind him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Zohl! Oh what a fascinating coincidence!” the voice said. It was a female tone. Tender, sweet, warm and lovingly. Wait. Why do I recognize this voice…?`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Geez! You scared the heck out of me!” His startled voice faded away. “Here I was, giving a soul a tour of this place before you had to scare me! You’re so annoying Nahfia.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Nahfia…? Who’s that…? And why does her voice sound so familar????`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `She noticed my soul-like body hanging behind Zohl. Maybe because my shyness rubbed too hard. I peeked around, still startled.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `But then I saw it. Well. Her.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `A resemblance so familar, it felt uncanny. Her appearance felt so green and warm, sort of like that dryad who took me in when I lived in the Sylphrelm.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“…..R-Raeya…?” her voice lingered onto me. “Is that you…?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I was uncertain if I wanted to respond. But I quietly stepped out from behind Zohl’s back and my eyes were hit with clarity. It was my adoptive mom. My parental figure who took me in for the time being back when I was a little Sylph.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“………m-mom……?…?!” I stuttered at the sight of her. Everything was coming back. I heard Zohl laugh.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I forgot about this~!” he teased me. “Meet Nahfia. The Spirit of Sylphs.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“She is also another Spirit of Creation like me, but she’s different! She has both my spirit typing, Celestriax, and Aloria’s too, Lyeceriax. We call her type the Nexzylkrai Spirit. Or the Nexus.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `WAIT THAT THE FU—?! My mind was spiraling. My adoptive mother, my parental figure, is a DIVINE SPIRIT?! And I wasn’t told about this?! All this time, the person who took me in—the person who took—this can’t be real….!!!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“She’s spiraling…oh no…!” I felt Nahfia come towards me and hugged me. She giggled lightly. I could feel her warmth, even now. I could smell her perfume of lavendar and honey. It was the same even when I grew up.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You didn’t have to expose me like that! Zohl you dummy!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I—I only wanted to introduce you! I didn’t know she was your adoptive daughter…” he chuckled slightly. Ah. I could sense his sarcasm.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Oh come here you~” Her arms reached around me for a hug.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’ve always wanted to see you. Even if under dire circumstances.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You might remember me as Dria, which is the name I told you back in our homeland.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `But just as I was able to speak again, tears escaped my eyes. Not because I let them. But because they came out of instinct, even though I wasn’t in my physical form. I clung onto Dria—no—Nahfia like I had missed her dearly. Why…? Because she showered me with <em>affirmation, loyalty, </em>and <em>validation, </em>even when I was at my lowest. She patted my head. Well, my soul-like head. I hugged tightly. Not wanting to let go of her. I don’t want to go back to the real world just yet.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Because I finally found what I thought I lost:`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `<em>Warmth that felt nostalgic. </em>`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Even if it wasn’t from Kydel or someone else. Or maybe perhaps Kydel’s warmth was more like a pristine gem. Unshakeable. But gentle.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Raeya..?” I heard Nahfia’s voice linger onto me again. I could feel her voice waver with love.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“It’s okay. You can break down here if you want. In my arms. Because you’re safe with me. And with us. Including Zohl.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I let myself go. The feeling of longingness came back, but in form of maturity. Because I once never thought about myself as ‘above others.’ I’m no better than me. Because I’m Raeya.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Raeya Flutters.`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `After a while, Nahfia was caught up to speed by Zohl. And with me bawling my eyes out in her arms, I couldn’t even muster the strength to talk. Let alone say <em>thank you </em>to her—who I still consider my mother at this point. Although she took care of me, I never really expressed my gratitude as much. She saw my physical form when Zohl made it visible.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `She knew what must be done to get me revived. Zohl left the two of us alone for a moment. He spotted a few of his friends and went to chat with them, since he mentioned a few names earlier, Morhv and Rimaea. Maybe he went to find them!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Dria…?” I silently tugged the hem of her sleeves. I was still calling her by her surface name.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Yeah..? What’s up? You can call me Nahfia now. Well, since the cat is out of the bag~,” her tone felt a little dismissive, but I ignored it. She probably has her own reasons. She took my hand and held it with grace. I wanted to bring up the elephant in the room, but I don’t know where to start. So I went with what was in my mind for a long time.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Why didn’t you stop….them…? The elves. My parents….?” I asked her, even with a little hesitancy.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Instead of answering me, she asked me, “<em>where do you think you came from</em>?” It was as if she wanted me to connect the dots, now that I’m an adult. Well. From what I understand, Nahfia is The Spirit of Sylphs. She created that lineage. The Sylph Massacre happed in 15 AD on Planet Hetra. Overpopulation. Elves began to hunt us Sylphs. They’re ruthless, violent, and accusatory. My parents was among them in the spree. They were killed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I am a descendant of her line. Well, is one, because I am here before her (hah). The Spirit of Sylphs, A Divine Spirit of creation who created my line, she can’t interfere. Because if she did, I wouldn’t be here. Divinity shouldn’t be meddled with humanity….<em>unlike a certain someone. </em>But overall, she can’t meddle with human affairs. That would lead to different consequences that could potentially spiral out of control.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Looks like you found your answer~” she teased me. “It’s true, I could’ve stopped them. But then you wouldn’t be here, nor would I come to be by your side.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“But since you are here with me right now, I can now wholeheartedly say this.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I tilted my head.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You are still my daughter, nonetheless. I don’t care what others say about you, or your Highland heritage. I just want to be by your side! To love you from afar even in your new chapter in life~”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `My heart swelled with warmth hearing her say that. Like a flower blooming into fruition.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Is this what…<em>affirmation…</em>feels like…? I’ve never…pinpointed that with precision before.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I turned my head around, feeling embarrased.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I am glad to see you alive and well. That’s all that matters to me.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You’re special sweetie. And I am sure your partner would agree too~”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I—?! Wha—? Hey!!! You can’t just tease me like that!” I slightly scoffed, but giggled. I saw her got up from sitting on the clouds. She patted my head again. Her soft touch made me feel at home.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Teehee~! I must be going now. The realm calls me back. Visit me when you can!~” she opened up a portal to our homeland: The Cloud Abode. The Sylphrelm. It goes by many names. And a lot of sylphs, wind spirits and faes live there. I want to go back, but I can’t. Now isn’t the time. Not yet at least.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I saw her go through despite our short time together, so I reached my hand out to speak up and say ‘<em>thank you for everything</em>,’ but the portal closed before I could get up. <em>Ah….dang</em>. There goes my chance to express my gratitude. Maybe some other time! I do want to go back to the real world and see Kydel.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I looked around the realm again. My heart eased and felt content. I could stay here. But I don’t want to. I want to go back and comfort Kydel.`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `A moment passed and I sat on the edge of the clouds my physical self was in. It lied still and motionless, like a person praying while laying down. I pondered for a bit.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Nahfia. That's an elegant name. Very Sylph coded. It was like she's the primordial wind. Like the Wind who Caught Everything.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `	I heard Zohl’s footsteps come back.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Hey. How was it with Nahfia?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I…,” I uttered, trying to form something. “It feels so surreal. Having her as my mother, let alone, being a Spirit like you…”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Hey, I was surprised as you too. So don’t leave me out!” he reassured me and let out a chuckle.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Now that you’ve situated well here, what do you think of this place?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `My hand shuffled around against the soft clouds I sat on. I looked around at the lively atmosphere. It felt tender. Unique. Kind of like a spiritual chapter had just opened up for me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“It’s nice. But I don’t want to stay here, even though I could.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He laughed at my enthusiasm, but he also knew I shouldn’t be here for too long.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Soooo~, do you want to go back to the real world?” He patted my shoulder and smirked.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Yes, I do! I don’t want to stay for so long!” I was a little excited, but nervous at the same time.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“You may not like what I’m about to say, but you gotta listen to the rules and agree to them,” Zohl told me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What’s required for you to be fully revived is that we’ll need to exchange something from you and give something to you. It’s called Equivalent Exchange. We’ll give you something back, but you need to give us something.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“What is it?” I asked, my head tilted out of curiosity.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“We’ll need some of your lifelines in order for this to work,” he responded seriously.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Since you’re a Sylph, you can live for 600 years, so I’ll be needing 150 of them for the revival to work.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“WHAT?!!” I was shocked. 150 years?! Ain’t no way. I can’t give up that much!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“No! That’s too much! Those years are important for all us Sylphs!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Raeya, I get that you treasure your life, since that’s your natural response. But we need this <em>revival </em>to work. In addition, we’ll be giving you something in return after the success it,” Zohl convinced me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“It’s not painful. You won’t feel anything at all. Maybe a tingling sensation, but it’s relaxing.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Please, trust me.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I was a little hesitant and I wanted to go back. But to give up 150 years of my lifespan?!? That’s so hard to take in!`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“How long does it take?” I asked him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Three years for you here in the Divine Realm,” he straight out responded.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Although time is nonexistent here, we measure days as years. Make it Divine Rules. Three Years in this place, but according to your body’s circadium system!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“But it’s different for time on Hetra. Kydel needs to wait three days.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He gave out a dry chuckle, “I know. It sucks. Don’t complain about it.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’ll let you decide and think on it. You don’t need to rush, but considering you want to see Kydel as soon as possible….just…consider it.”`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He left me to my own thoughts while he was still around me, keeping me company. He was next to my physical body tendering to it to make preparations. Also, he stripped me nude!!! How dare he! I’m being sarcastic though. It’s probably part of the ritual.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I couldn't find the words to express myself. My thoughts were all jumbled up. All my desires right now was to return to Hetra. I hope to be there for Kydel and offer solace, but it's not possible (at least). Because Zohl said I need to give 150 years of my life, I must dedicate it for this to be successful. My mind cycled between these thoughts so much, my brain hurt. However, I was confident about my final decision. So instead of trying to stress about it, I gave him an answer.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Okay. But make the reward worth it!” I came to an agreement. Zohl got up and touched the cloud my body was on.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Follow me,” he gestured to me. The bed of clouds followed him.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `We both flew past the vast scene and lands of the realm, ranging from colorful places full of life. There were many spirits playing and talking amongst each other within my sight. Divine creatures roamed the place, and I saw them run and fly at the same time.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Zohl flew up and I followed. As we flew farther, he landed onto a cloud on his right. There stood a fountain that was barely visible from the ground. It was grand, and yellow-like divine water spilled from the top of the fountain to the bottom. Suddenly, a looming presence appeared before us.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `He bowed down again before, and I followed along.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Right! I forgot why you two were here for!” The King appeared out of nowhere again.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Eek!” I jumped.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Stop scaring me like that!!”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `The two of them laughed at my embarrassment.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“All I ask is for my friend to be revived. She sacrificed herself to protect the one she loved,” Zohl requested.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `The King looked like a giant turtle-lion like creature, a Zaratan. It was bigger than an average one, which doesn’t exist on planet Hetra currently. I kept kneeling, as the appearance of the King startled me, since I could feel his stare and judgment.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Please, rise,” The King ordered me. I slowly got up and bowed slightly again.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Has Zohl told you the requirements for this to work?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Yes,” I replied.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“May I also add, in order for this to work, this entire process will undergo Incandescentry. The action of restoring the body’s motor and strength, along with other physical and internal functions. After that is done, a coma is needed for the remaining years of revival,” The King told me in advance.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Now, are you sure you are ready?”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `Another hesitant look showed on my face. But I didn’t want to wait.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Yes I am,” I agreed.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `The King then lifted my body gently from the cloud of beds into the fountain’s water gently. I observed as the outer bruises faded, and one by one, parts of my body healed. All that was left was me, in my astral form.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“If you may, please step into the fountain,” The King asked of me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I went into the fountain and placed my feet against my physical ones. This allowed me to inhabit my body.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Raeya, how are you feeling?” Zohl asked me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’m excited, but nervous..! Thank you for your concern.” I was a little happy he was doing this for me. Not just for me, but for Kydel.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’m glad you’re adjusting well to us,” The King told me.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“Please, continue to be friends with my dearest Zohl.”`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `I smiled happily as I laid down against my body. I could feel the water trickle around my soul and my main form. It felt cool and just right, not too hot or too cold. I placed my arms on the chest the way the King laid them. I could feel my body submerge underneath the water as I closed my eyes.`}} />
      <p className="font-body text-sm text-[#c8c2ba] leading-[1.85] indent-8" dangerouslySetInnerHTML={{__html: `“I’ll see you after three years,” Zohl told me before my soul went to sleep. I had a smile on my face before I went into a deep, deep slumber.`}} />
      <div className="my-8 flex items-center gap-4"><div className="flex-1 h-px bg-[#2e2b26]" /><span className="text-[#c9a84c]/40 text-xs">✦</span><div className="flex-1 h-px bg-[#2e2b26]" /></div>
      <p className="font-body text-sm text-[#c9a84c] leading-[1.85] italic indent-8" dangerouslySetInnerHTML={{__html: `Sometimes, I keep forgetting that Zohl is a powerful Divine Spirit. Not some god or some lackey. His role as one might be important, but, humility is way more important than anything else.`}} />
      <p className="font-body text-sm text-[#c9a84c] leading-[1.85] italic indent-8" dangerouslySetInnerHTML={{__html: `But he's also my friend. <em>A good friend. </em>`}} />

      {/* Chapter navigation */}
      <div className="mt-16 pt-8 border-t border-[#2e2b26] grid grid-cols-2 gap-4">
          <Link to="/bookshelf/ministories/damsellete-of-the-wind/episode-3" className="group flex flex-col text-left border border-[#2e2b26] rounded-sm px-4 py-3 bg-[#131210] hover:border-[#c9a84c]/40 hover:bg-[#1a1814] transition-all duration-200"><span className="font-body text-[9px] tracking-widest uppercase text-[#4a4844] mb-1">← Previous</span><span className="font-display text-xs text-[#f2ebeb] group-hover:text-[#c9a84c] transition-colors">EP III — Raeya&#39;s Loving Sacrifice</span></Link>
          <Link to="/bookshelf/ministories/damsellete-of-the-wind/episode-5" className="group flex flex-col text-right border border-[#2e2b26] rounded-sm px-4 py-3 bg-[#131210] hover:border-[#c9a84c]/40 hover:bg-[#1a1814] transition-all duration-200 ml-auto"><span className="font-body text-[9px] tracking-widest uppercase text-[#4a4844] mb-1">Next →</span><span className="font-display text-xs text-[#f2ebeb] group-hover:text-[#c9a84c] transition-colors">EP V — Back From the Dead</span></Link>
      </div>
    </div>
  );
}
