// ============================================================
// Footer — extracted from the old Layout.tsx footer.
// Static, but kept as a React island for parity (the © year is
// computed at render). Anti-piracy notice + Dead Shard Continuity.
//
// Word Count Tracker — loreWordCount.json is regenerated by
// scripts/count-lore-words.mjs on every `dev`/`build` run (see
// package.json), so these totals silently re-sync themselves whenever
// lore, Vol 0, or ministory content is added or edited. No manual
// step required. Lore, Vol0GenesisLore (Vol 0 - HTHGOE), and Ministory
// are each tracked separately (Ministory = finished Hibryds Ministories
// pages only; TBD scaffolds sit in the "Not Yet Tallied" bucket
// alongside Bookshelf/Multimedia), then summed into "Overall Word Count".
// ============================================================
import loreStats from '../data/loreWordCount.json'

export default function Footer() {
  return (
    <footer className="border-t border-[#2e2b26] py-6 mt-12">
      <div className="max-w-[1200px] mx-auto px-5 flex flex-col items-center gap-5">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 w-full">
          <p className="font-body text-[0.6rem] text-[#4a4844] tracking-wider uppercase">
            © {new Date().getFullYear()} The Hibrythian Saga ·{' '}
            <a
              href="https://www.alarkiusej.com/"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[#c9a84c] transition-colors duration-150"
            >
              Alarkius Elvya Jay
            </a>
          </p>
          <div className="gold-rule hidden sm:block" aria-hidden="true" />
          <p className="font-body text-[0.6rem] text-[#4a4844] tracking-wider">
            All Lore &amp; Worldbuilding Are Rights Reserved.
          </p>
        </div>
        <div className="lore-stats-card w-full" role="note" aria-label="Word count tracker">
          <p className="lore-stats-title">[ Word Count Tracker ]</p>
          <p className="lore-stats-body">
            Lore Word Count: {loreStats.loreWords.toLocaleString('en-US')} Words Across {loreStats.lorePages.toLocaleString('en-US')} Pages.<br />
            Vol0GenesisLore Word Count: {loreStats.vol0Words.toLocaleString('en-US')} Words Across {loreStats.vol0Pages.toLocaleString('en-US')} Pages.<br />
            Ministory Word Count: {loreStats.ministoryWords.toLocaleString('en-US')} Words Across {loreStats.ministoryPages.toLocaleString('en-US')} Pages.<br />
            Overall Word Count: {loreStats.overallWords.toLocaleString('en-US')} Words Across {loreStats.overallPages.toLocaleString('en-US')} Pages.<br />
            Special Characters Counted: {loreStats.overallSpecialCharacterCount.toLocaleString('en-US')}.<br />
            Not Yet Tallied: Bookshelf ({loreStats.excluded.Bookshelf.toLocaleString('en-US')} Pages, Mostly TBD), Ministories ({loreStats.excluded.Ministories.toLocaleString('en-US')} Pages, TBD) &amp; Multimedia ({loreStats.excluded.Multimedia.toLocaleString('en-US')} Pages) —{' '}
            {loreStats.excluded.total.toLocaleString('en-US')} Pages In Total.
          </p>
        </div>
        <div className="piracy-notice w-full" role="note" aria-label="Anti-piracy notice">
          <p className="piracy-notice-title">[The Dead Shard Continuity Notice — Class C Piracy Violation]</p>
          <p className="piracy-notice-body">
            Unauthorized redistribution of Hibrythiea-Encoded lore and Stories has been detected.<br />
            &nbsp;&nbsp;&nbsp;&nbsp;You're not trying to pirate this entire site, are you… <em>user·? Do you really want to find out the hard way?</em><br />
            This universe is heavily protected! Reuploading or stealing content will lead to legal
            consequences — and yes, we can track it. Don't try and fight{' '}
            <a href="/characters" target="_self">Hunter Noxx</a>,{' '}
            <a href="/characters" target="_self">Zohl</a>, or{' '}
            <a href="/characters" target="_self">Kydel Rhunes</a>.
            {' '}Or any of our characters. They will obliterate you to smithereens!
            For More Information, contact the author with this: contact@alarkiusej.com
          </p>
        </div>
      </div>
    </footer>
  )
}
